### ISSUE TITLE
Watch changes and restart

### ISSUE THREAD

**Issue by trsouz** [litixsoft/generator-lxgo#1]
Great generator! Thanks for this.

Maybe create tasks to watch for changes in files and restart the process. What you think?

**Comment by 4kochi** [comment]
Good idea. We have planned this anyway but this generator is under development yet. We are currently working on a solution for the vendoring which is based on https://getgb.io. After finishing this we will refactor the tasks. And add new ones linke serve and watch.

So I'm closing this for now as you can expect the task to be implemented soon.
